app = 'mezza'
primary_region = 'sjc'

[build]
  dockerfile = "./server/Dockerfile"
  build-target = "prod"

[env]
  DJANGO_DEBUG = "false"
  BASE_URL = "https://demo.django-render.org"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
