app = 'crowflow'
primary_region = 'lhr'

[build]
  dockerfile = './server/Dockerfile'
  build-target = 'prod'

[env]
  BASE_URL = 'https://crowflow.io'
  DJANGO_DEBUG = 'false'
  DJANGO_ALLOWED_HOSTS = 'crowflow.io'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
