app = 'mezza-studio'
primary_region = 'bos'

[build]
  dockerfile = './server/Dockerfile'
  build-target = 'prod'

[env]
  BASE_URL = 'https://studio.mezzahq.com'
  DJANGO_ALLOWED_HOSTS = 'mezza-studio.fly.dev,studio.mezzahq.com'
  DJANGO_DEBUG = 'false'
  BACKBLAZE_BUCKET = 'mezza-uploads'
  BACKBLAZE_REGION = 'us-east-005'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
