# Generated by Django 5.0.7 on 2024-08-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mezza", "0001_initial"),
        ("mezzamedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacebookPost",
            fields=[
                (
                    "basepost_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezzasocial.basepost",
                    ),
                ),
                ("body", models.JSONField()),
            ],
            bases=("mezzasocial.basepost",),
        ),
        migrations.CreateModel(
            name="LinkedInPost",
            fields=[
                (
                    "basepost_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezzasocial.basepost",
                    ),
                ),
                ("body", models.JSONField()),
            ],
            bases=("mezzasocial.basepost",),
        ),
        migrations.CreateModel(
            name="XPost",
            fields=[
                (
                    "basepost_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezzasocial.basepost",
                    ),
                ),
                ("text", models.TextField()),
            ],
            bases=("mezzasocial.basepost",),
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.workspace",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="basepost",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mezzasocial.channel"
            ),
        ),
        migrations.CreateModel(
            name="YoutubeVideo",
            fields=[
                (
                    "basepost_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezzasocial.basepost",
                    ),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezzamedia.imagefile",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezzamedia.videofile",
                    ),
                ),
            ],
            bases=("mezzasocial.basepost",),
        ),
    ]
