# Generated by Django 5.0.7 on 2024-08-15 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crowflowflows", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stage",
            options={"ordering": ["space", "order"]},
        ),
    ]
