# Generated by Django 5.0.7 on 2024-08-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezzaprojects", "0003_project_space"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["stage__order", "order"]},
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
