# Generated by Django 5.0.7 on 2024-08-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LongFormText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("slug", models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=50)),
                ("slug", models.TextField(max_length=50)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentTypeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mezza.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "component")},
            },
        ),
        migrations.AddField(
            model_name="contenttype",
            name="components",
            field=models.ManyToManyField(
                related_name="+",
                through="mezza.ContentTypeComponent",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="contenttype",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="mezza.workspace"
            ),
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.contenttype",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.workspace",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="contenttype",
            unique_together={("workspace", "slug")},
        ),
    ]
