# Generated by Django 5.0.7 on 2024-08-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiofileasset",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_assets",
                to="mezza.audiofile",
            ),
        ),
        migrations.AlterField(
            model_name="documentfileasset",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_assets",
                to="mezza.documentfile",
            ),
        ),
        migrations.AlterField(
            model_name="imagefileasset",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_assets",
                to="mezza.imagefile",
            ),
        ),
        migrations.AlterField(
            model_name="videofileasset",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_assets",
                to="mezza.videofile",
            ),
        ),
    ]
