# Generated by Django 5.0.7 on 2024-08-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortFormText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
