# Generated by Django 5.0.7 on 2024-08-24 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="pipeline",
        ),
        migrations.DeleteModel(
            name="Pipeline",
        ),
    ]
