# Generated by Django 5.0.7 on 2024-08-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0002_remove_project_pipeline_delete_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.CharField(
                choices=[
                    ("100-ideas", "Ideas"),
                    ("200-scripting", "Scripting"),
                    ("300-filming", "Filming"),
                    ("400-editing", "Editing"),
                    ("500-completed", "Completed"),
                ],
                default="100-ideas",
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["stage", "order"]},
        ),
        migrations.DeleteModel(
            name="Stage",
        ),
    ]
