# Generated by Django 5.0.7 on 2024-08-24 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0002_alter_audiofileasset_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="name",
            new_name="title",
        ),
    ]
