# Generated by Django 5.0.7 on 2024-08-01 22:38

from django.db import migrations


def create_default_workspace(apps, schema_editor):
    Workspace = apps.get_model("mezza", "Workspace")
    Workspace.objects.get_or_create(slug="default", defaults={"name": "Default"})


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0002_shortformtext"),
    ]

    operations = [
        migrations.RunPython(create_default_workspace, migrations.RunPython.noop),
    ]
