# Generated by Django 5.0.7 on 2024-08-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0003_default_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mezza.campaign",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="mezza.content",
                    ),
                ),
            ],
            options={
                "unique_together": {("content", "campaign")},
            },
        ),
        migrations.AddField(
            model_name="content",
            name="campaigns",
            field=models.ManyToManyField(
                related_name="content",
                through="mezza.ContentCampaign",
                to="mezza.campaign",
            ),
        ),
    ]
