# Generated by Django 5.0.7 on 2024-08-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0003_alter_project_stage_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AlterField(
            model_name="project",
            name="stage",
            field=models.CharField(
                choices=[
                    ("scripting", "Scripting"),
                    ("filming", "Filming"),
                    ("editing", "Editing"),
                    ("completed", "Completed"),
                ],
                default="scripting",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="mezza.space",
                    ),
                ),
            ],
        ),
    ]
