# Generated by Django 5.0.7 on 2024-08-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0003_rename_name_asset_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="videofile",
            name="frame_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
