# Generated by Django 5.0.7 on 2024-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0004_alter_project_options_alter_project_stage_idea"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="order",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
