# Generated by Django 5.0.7 on 2024-08-30 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0004_videofile_frame_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AudioFileAsset",
            new_name="AudioAsset",
        ),
        migrations.RenameModel(
            old_name="DocumentFileAsset",
            new_name="DocumentAsset",
        ),
        migrations.RenameModel(
            old_name="ImageFileAsset",
            new_name="ImageAsset",
        ),
        migrations.RenameModel(
            old_name="VideoFileAsset",
            new_name="VideoAsset",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="library",
        ),
        migrations.AddField(
            model_name="asset",
            name="space",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="mezza.space",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AssetLibrary",
        ),
    ]
