# Generated by Django 5.0.7 on 2024-08-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0005_rename_audiofileasset_audioasset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="frame_count",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="audio_streams",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videofile",
            name="audio_streams",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="videofile",
            name="video_stream",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
