# Generated by Django 5.0.7 on 2024-08-30 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0006_remove_audiofile_duration_remove_videofile_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="script",
        ),
    ]
