# Generated by Django 5.0.7 on 2024-08-30 23:09

import mezza.models.projects
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0007_remove_project_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="script",
            field=models.JSONField(default=mezza.models.projects.get_default_script),
        ),
    ]
