# Generated by Django 5.0.7 on 2024-08-30 23:44

from django.db import migrations, models

import mezza.models.files


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0008_project_script"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagefile",
            name="thumbnail_file",
            field=models.FileField(
                null=True, upload_to=mezza.models.files.get_image_thumbnail_upload_path
            ),
        ),
        migrations.AddField(
            model_name="videofile",
            name="thumbnail_file",
            field=models.FileField(
                null=True, upload_to=mezza.models.files.get_video_thumbnail_upload_path
            ),
        ),
    ]
