# Generated by Django 5.0.7 on 2024-10-05 11:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0009_imagefile_thumbnail_file_videofile_thumbnail_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="due_date",
            new_name="release_date",
        ),
    ]
