# Generated by Django 5.0.7 on 2024-10-05 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0010_rename_due_date_project_release_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="stage",
        ),
    ]
