# Generated by Django 5.0.7 on 2024-10-05 12:23

import django.db.models.deletion
import mezza.models.assets
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza", "0011_remove_project_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezza.asset",
                    ),
                ),
                (
                    "content",
                    models.JSONField(default=mezza.models.assets.get_default_script),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("mezza.asset",),
        ),
        migrations.RemoveField(
            model_name="project",
            name="script",
        ),
    ]
