# Generated by Django 5.2 on 2025-04-19 13:33

import django.db.models.deletion
import uuid_extensions.uuid7
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mezzafiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="thumbnail_blob",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mezzafiles.fileblob",
            ),
        ),
        migrations.AlterField(
            model_name="fileblob",
            name="uuid",
            field=models.UUIDField(
                default=uuid_extensions.uuid7, primary_key=True, serialize=False
            ),
        ),
    ]
