# Generated by Django 5.2 on 2025-04-19 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mezzafiles", "0002_file_thumbnail_blob_alter_fileblob_uuid"),
        ("mezzaworkspaces", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together={("workspace", "name")},
        ),
    ]
