# Generated by Django 5.0.7 on 2024-08-13 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vianospaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="vianospaces.space",
                    ),
                ),
            ],
        ),
    ]
