# Generated by Django 5.0.6 on 2024-05-26 11:51

import django.db.models.deletion
from django.db import migrations, models

import mezza.media.models


class Migration(migrations.Migration):
    dependencies = [
        ("mezza_media", "0002_mediaasset_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thumbnail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="thumbnails")),
            ],
        ),
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(upload_to=mezza.media.models.get_upload_to),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="thumbnail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mezza_media.thumbnail",
            ),
        ),
    ]
