# Generated by Django 5.0.7 on 2024-08-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("mezza", "0004_campaign_contentcampaign_content_campaigns"),
        ("mezzamedia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezza.workspace",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mezza.content",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="mezzayoutube.youtubechannel",
                    ),
                ),
                (
                    "thumbnail_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezzamedia.imagefile",
                    ),
                ),
                (
                    "video_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mezzamedia.videofile",
                    ),
                ),
            ],
            bases=("mezza.content",),
        ),
    ]
