# Generated by Django 5.0.7 on 2024-08-15 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowflowfiles", "0001_initial"),
        ("crowflowprojects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="final_video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crowflowfiles.videofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="script",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="crowflowfiles.imagefile",
            ),
        ),
        migrations.CreateModel(
            name="Footage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footage",
                        to="crowflowprojects.project",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="crowflowfiles.videofile",
                    ),
                ),
            ],
        ),
    ]
