# Generated by Django 5.0.7 on 2024-08-15 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crowflowprojects", "0002_project_description_project_due_date_and_more"),
        ("crowflowspaces", "0002_spaceuser_space_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="space",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="crowflowspaces.space",
            ),
            preserve_default=False,
        ),
    ]
